name: Run Application and Database

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
          DB_POSTGRESS_PASSWORD: ${{ secrets.DB_POSTGRESS_PASSWORD }}
          DB_POSTGRESS_DIALECT: ${{ secrets.DB_POSTGRESS_DIALECT }}
          DB_POSTGRESS_HOST: ${{ secrets.DB_POSTGRESS_HOST }}
          DB_POSTGRESS_PORT: ${{ secrets.DB_POSTGRESS_PORT }}
          DB_POSTGRESS_DATABASE: ${{ secrets.DB_POSTGRESS_DATABASE }}
          DB_POSTGRESS_USERNAME: ${{ secrets.DB_POSTGRESS_USERNAME }}

        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Deploy to Heroku
            uses: akhileshns/heroku-deploy@v3.12.12
            with:
              heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
              heroku_app_name: "pagarme-test"
              heroku_email: "leoanjossantos2@gmail.com"
              env_file: ".env"